arm_controller_name: "arm_controller"
wait_server_timeout_sec: 5.0
poll_rate_hz: 50.0

backend_controllers:
  - name: "pp_arm_controller"
    action_ns: "/pp_arm_controller/follow_joint_trajectory"
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4

  - name: "canopen_arm_controller"
    action_ns: "/canopen/canopen_arm_controller/follow_joint_trajectory"
    joints:
      - arm_joint_5
      - arm_joint_6
