controller_list:
  - name: fake_main_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - zhua1
      - zhua2
initial:  # Define initial robot poses per group
  - group: main_arm
    pose: up
  - group: gripper
    pose: close