bus:
  device: can0
  loopback: false
  driver_plugin: can::SocketCANInterface

sync:
  interval_ms: 10
  overflow: 0

heartbeat:
  rate: 10
  msg: "700#05"

defaults:
  eds_pkg: yiyou_canopen
  eds_file: "config/YiyouServo_V1.4.eds"
  dcf_overlay:
    "6060": "01"
    "6081": "B00D0500"
    "6083": "B00D0500"
    "6084": "B00D0500"

nodes:
  arm_joint_5:
    id: 1
  arm_joint_6:
    id: 2
  flipper_1:
    id: 3
  flipper_2:
    id: 4
  flipper_3:
    id: 5
  flipper_4:
    id: 6
