bus:
  device: can0
  loopback: false
  driver_plugin: can::SocketCANInterface

sync:
  interval_ms: 10
  overflow: 0

heartbeat:
  rate: 10
  msg: "700#05"

defaults:
  eds_pkg: yiyou_canopen
  eds_file: "config/YiyouServo_V1.4_csp.eds"
  dcf_overlay:
    # Enable RPDO1/TPDO1 channels and disable 2/3/4.
    "1400sub1": "0x00000205"
    "1800sub1": "0x40000185"
    "1401sub1": "0x80000305"
    "1402sub1": "0x80000405"
    "1403sub1": "0x80000505"
    "1801sub1": "0xC0000285"
    "1802sub1": "0xC0000385"
    "1803sub1": "0xC0000485"
    # Force CSP mode (8) on every init.
    "6060": "8"

nodes:
  arm_joint_5:
    id: 1
  arm_joint_6:
    id: 2
  flipper_1:
    id: 3
  flipper_2:
    id: 4
  flipper_3:
    id: 5
  flipper_4:
    id: 6
