joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

canopen_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_joint_5
    - arm_joint_6
  constraints:
    goal_time: 5.0
    arm_joint_5: {goal: 0.02}
    arm_joint_6: {goal: 0.02}

flipper_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - flipper_1
    - flipper_2
    - flipper_3
    - flipper_4
